// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as SpeedEditorService from "./speededitorservice.js";
export {
    SpeedEditorService
};

export {
    Heartbeat,
    Key
} from "./models.js";

import * as $models from "./models.js";

/**
 * KeyGrid represents the keyboard layout as map[column][row]Key
 * @typedef {$models.KeyGrid} KeyGrid
 */
