// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Heartbeat {
    /**
     * Creates a new Heartbeat instance.
     * @param {Partial<Heartbeat>} [$$source = {}] - The source object to create the Heartbeat.
     */
    constructor($$source = {}) {
        if (!("Connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Connected"] = false;
        }
        if (!("Error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Error"] = "";
        }
        if (!("Serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Serial"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Heartbeat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Heartbeat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Heartbeat(/** @type {Partial<Heartbeat>} */($$parsedSource));
    }
}
