// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Heartbeat {
    /**
     * Creates a new Heartbeat instance.
     * @param {Partial<Heartbeat>} [$$source = {}] - The source object to create the Heartbeat.
     */
    constructor($$source = {}) {
        if (!("Connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Connected"] = false;
        }
        if (!("Error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Error"] = "";
        }
        if (!("Serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Serial"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Heartbeat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Heartbeat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Heartbeat(/** @type {Partial<Heartbeat>} */($$parsedSource));
    }
}

/**
 * Key represents a key on the Speed Editor with its position and dimensions
 */
export class Key {
    /**
     * Creates a new Key instance.
     * @param {Partial<Key>} [$$source = {}] - The source object to create the Key.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("subText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subText"] = "";
        }
        if (!("row" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["row"] = 0;
        }
        if (!("col" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["col"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Key instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Key}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Key(/** @type {Partial<Key>} */($$parsedSource));
    }
}

/**
 * KeyGrid represents the keyboard layout as map[column][row]Key
 * @typedef {{ [_ in string]?: { [_ in `${number}`]?: Key } }} KeyGrid
 */

export class ledStatus {
    /**
     * Creates a new ledStatus instance.
     * @param {Partial<ledStatus>} [$$source = {}] - The source object to create the ledStatus.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ledStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ledStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ledStatus(/** @type {Partial<ledStatus>} */($$parsedSource));
    }
}
