// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetKeys returns all keys from the Speed Editor layout organized by column and row
 * @returns {$CancellablePromise<$models.KeyGrid>}
 */
export function GetKeys() {
    return $Call.ByID(3284359353).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} keyId
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetKeyLedBehaviour(keyId, mode) {
    return $Call.ByID(1929953512, keyId, mode);
}

/**
 * @param {number} keyId
 * @param {time$0.Time} litAt
 * @param {time$0.Duration} litFor
 * @returns {$CancellablePromise<void>}
 */
export function SetKeyLit(keyId, litAt, litFor) {
    return $Call.ByID(921159981, keyId, litAt, litFor);
}

// Private type creation functions
var $$createType0 = /** @type {(...args: any[]) => any} */(function $$initCreateType0(...args) {
    if ($$createType0 === $$initCreateType0) {
        $$createType0 = $$createType3;
    }
    return $$createType0(...args);
});
const $$createType1 = $models.Key.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
