//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../JamesBalazs/speed-editor-rebind/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "consolidateJogLeds": $$createType0,
        "consolidateLeds": $$createType0,
        "heartbeat": $$createType1,
        "keyPress": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = main$0.Heartbeat.createFrom;
const $$createType2 = $Create.Array($Create.Any);

configure();
